name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Gradle build (Documents)
      run: ./gradlew javadoc
    - name: Run unit tests
      run: ./gradlew check
